### ISSUE TITLE
Dynamic batch_size

### ISSUE THREAD

**Issue by NoumanSaleem** [logstash-plugins/logstash-output-sqs#11]
Feature request for dynamic `batch_size` to work around SQS limitation of `batch size max == single message size max`

http://docs.aws.amazon.com/sdkforruby/api/Aws/SQS/Client.html#send_message_batch-instance_method

> The maximum allowed individual message size is 256 KB (262,144 bytes).
> The maximum total payload size (i.e., the sum of all a batch's individual message lengths) is also 256 KB (262,144 bytes).

related issue: https://github.com/logstash-plugins/logstash-output-sqs/issues/10

**Comment by ph** [comment]
Since 4.0.0, there is a check in place for ajusting the batch size.
