### ISSUE TITLE
Logstash Delete/trim Larger size logs

### ISSUE THREAD

**Issue by PraveenJayakrishnakumar** [logstash-plugins/logstash-output-sqs#5]
We are using SQS output, but unfortunately SQS allows only 256K size per messages/batch. Does logstash is providing any features to remove/trim larger size log messages, if it reaches beyond certain characters limits.

**Comment by ph** [comment]
The plugin will now adjust the size of the batch to go around the 256k limits and yield log when it goes over.

**Comment by jrgns** [comment]
Confirmed. You'll get an error message like follows in the logs:

```
[2017-01-10T21:29:15,575][WARN ][logstash.outputs.sqs     ] Message exceeds maximum length and will be dropped {:message_size=>264145}
```
